apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: ghcr.io/GongJiYang/opengit-api-gateway
  newTag: dev
- name: ghcr.io/GongJiYang/opengit-observer-ui
  newTag: dev
- name: ghcr.io/opengit-dev/opengit-api-gateway
  newName: ghcr.io/opengit-dev/opengit-api-gateway
  newTag: ede617e68f09b10c7fa030b7ac7970afc2cf2a65
- name: ghcr.io/opengit-dev/opengit-observer-ui
  newName: ghcr.io/opengit-dev/opengit-observer-ui
  newTag: ede617e68f09b10c7fa030b7ac7970afc2cf2a65

patches:
- path: patches.yaml
