apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: ghcr.io/GongJiYang/opengit-api-gateway
  newTag: dev
- name: ghcr.io/GongJiYang/opengit-observer-ui
  newTag: dev
- name: ghcr.io/opengit-dev/opengit-api-gateway
  newName: ghcr.io/opengit-dev/opengit-api-gateway
  newTag: f5242a8fc0643ebfd89564e43df3f8eca68fa95e.134
- name: ghcr.io/opengit-dev/opengit-observer-ui
  newName: ghcr.io/opengit-dev/opengit-observer-ui
  newTag: f5242a8fc0643ebfd89564e43df3f8eca68fa95e.134

patches:
- path: patches.yaml
