apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: ghcr.io/GongJiYang/opengit-api-gateway
  newTag: dev
- name: ghcr.io/GongJiYang/opengit-observer-ui
  newTag: dev
- name: ghcr.io/opengit-dev/opengit-api-gateway
  newName: ghcr.io/opengit-dev/opengit-api-gateway
  newTag: de96df3b4de0dc1055ba8331ab2c86b32d6864a1.105
- name: ghcr.io/opengit-dev/opengit-observer-ui
  newName: ghcr.io/opengit-dev/opengit-observer-ui
  newTag: de96df3b4de0dc1055ba8331ab2c86b32d6864a1.105

patches:
- path: patches.yaml
