apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: ghcr.io/GongJiYang/opengit-api-gateway
  newTag: staging
- name: ghcr.io/GongJiYang/opengit-observer-ui
  newTag: staging
- name: ghcr.io/opengit-dev/opengit-api-gateway
  newName: ghcr.io/opengit-dev/opengit-api-gateway
  newTag: 7f5c8fa60c3134c86b6ae98e5c32fc5efad11d7e.130
- name: ghcr.io/opengit-dev/opengit-observer-ui
  newName: ghcr.io/opengit-dev/opengit-observer-ui
  newTag: 7f5c8fa60c3134c86b6ae98e5c32fc5efad11d7e.130

patches:
- path: patches.yaml
