apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: ghcr.io/GongJiYang/opengit-api-gateway
  newTag: staging
- name: ghcr.io/GongJiYang/opengit-observer-ui
  newTag: staging
- name: ghcr.io/opengit-dev/opengit-api-gateway
  newName: ghcr.io/opengit-dev/opengit-api-gateway
  newTag: da8dbf80f70e2a827a2bb096974f34ff542ae591.133
- name: ghcr.io/opengit-dev/opengit-observer-ui
  newName: ghcr.io/opengit-dev/opengit-observer-ui
  newTag: da8dbf80f70e2a827a2bb096974f34ff542ae591.133

patches:
- path: patches.yaml
