apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: ghcr.io/GongJiYang/opengit-api-gateway
  newTag: staging
- name: ghcr.io/GongJiYang/opengit-observer-ui
  newTag: staging
- name: ghcr.io/opengit-dev/opengit-api-gateway
  newName: ghcr.io/opengit-dev/opengit-api-gateway
  newTag: 46b5c17914558c9f86cb2c96d3f1114a05642966.118
- name: ghcr.io/opengit-dev/opengit-observer-ui
  newName: ghcr.io/opengit-dev/opengit-observer-ui
  newTag: 46b5c17914558c9f86cb2c96d3f1114a05642966.118

patches:
- path: patches.yaml
