apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: ghcr.io/opengit-dev/opengit-api-gateway
  newName: ghcr.io/opengit-dev/opengit-api-gateway
  newTag: 425204f608ce02d712bad8117e769c04e6f17768
- name: ghcr.io/opengit-dev/opengit-observer-ui
  newName: ghcr.io/opengit-dev/opengit-observer-ui
  newTag: 425204f608ce02d712bad8117e769c04e6f17768

patchesJson6902:
- path: patches.yaml
  target:
    kind: Ingress
    name: opengit
