apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: ghcr.io/opengit-dev/opengit-api-gateway
  newName: ghcr.io/opengit-dev/opengit-api-gateway
  newTag: befe4240be2dd603bc54d20d1bf8796929a9fca8
- name: ghcr.io/opengit-dev/opengit-observer-ui
  newName: ghcr.io/opengit-dev/opengit-observer-ui
  newTag: befe4240be2dd603bc54d20d1bf8796929a9fca8

patchesJson6902:
- path: patches.yaml
  target:
    kind: Ingress
    name: opengit
