apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: ghcr.io/opengit-dev/opengit-api-gateway
  newName: ghcr.io/opengit-dev/opengit-api-gateway
  newTag: 3f2e053bb76aeeb620977f76957c42e58a1630c9.67
- name: ghcr.io/opengit-dev/opengit-observer-ui
  newName: ghcr.io/opengit-dev/opengit-observer-ui
  newTag: 3f2e053bb76aeeb620977f76957c42e58a1630c9.67

patchesJson6902:
- path: patches.yaml
  target:
    kind: Ingress
    name: opengit
