apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opengit-prod
spec:
  project: default
  source:
    repoURL: https://github.com/GongJiYang/opengit-infra.git
    targetRevision: main
    path: overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: opengit
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
