apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  APP_ENV: "production"
  QDRANT_URL: "./agenthub_data/qdrant"
  APP_ENABLE_INDEXER: "0"
  APP_ENABLE_SANDBOX: "0"
  RUN_SCHEDULER: "0"
  RUN_MIGRATIONS: "0"
